"""initial_schema

Revision ID: 0c5b878bb87a
Revises: 
Create Date: 2026-06-01 16:48:27.413760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c5b878bb87a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.String(length=50), nullable=False),
    sa.Column('camera_id', sa.String(length=50), nullable=False),
    sa.Column('visitor_id', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('zone_id', sa.String(length=50), nullable=True),
    sa.Column('dwell_ms', sa.Integer(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id_token', sa.String(length=100), nullable=True),
    sa.Column('track_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('event_id', name='uq_events_event_id')
    )
    op.create_index('idx_events_event_type', 'events', ['event_type'], unique=False)
    op.create_index('idx_events_is_staff', 'events', ['is_staff'], unique=False)
    op.create_index('idx_events_store_timestamp', 'events', ['store_id', 'timestamp'], unique=False)
    op.create_index('idx_events_visitor_id', 'events', ['visitor_id'], unique=False)
    op.create_table('pos_transactions',
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('store_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('basket_value_inr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('matched_visitor_id', sa.String(length=50), nullable=True),
    sa.Column('matched_session_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('visitor_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('visitor_id', sa.String(length=50), nullable=False),
    sa.Column('store_id', sa.String(length=50), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_converted', sa.Boolean(), nullable=False),
    sa.Column('total_events', sa.Integer(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('idx_visitor_sessions_store_entry', 'visitor_sessions', ['store_id', 'entry_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_visitor_sessions_store_entry', table_name='visitor_sessions')
    op.drop_table('visitor_sessions')
    op.drop_table('pos_transactions')
    op.drop_index('idx_events_visitor_id', table_name='events')
    op.drop_index('idx_events_store_timestamp', table_name='events')
    op.drop_index('idx_events_is_staff', table_name='events')
    op.drop_index('idx_events_event_type', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
