"""add_global_visitor_matches

Revision ID: 8399e992360e
Revises: 0c5b878bb87a
Create Date: 2026-06-03 10:37:43.775231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8399e992360e'
down_revision: Union[str, Sequence[str], None] = '0c5b878bb87a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_visitor_matches',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('global_person_id', sa.String(length=50), nullable=False),
    sa.Column('local_tracker_id', sa.String(length=100), nullable=False),
    sa.Column('camera_id', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_camera', sa.String(length=50), nullable=True),
    sa.Column('destination_camera', sa.String(length=50), nullable=True),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_visitor_matches')
    # ### end Alembic commands ###
